export const data=[
{
id: 1,
coffeeName: "Montreal",
searchTerm: "Cappuccino",
description: "A cappuccino is the perfect balance of espresso, steamed milk and foam. This coffee is all about the structure and the even splitting of all elements into equal thirds. An expertly made cappuccino should be rich, but not acidic and have a mildly sweet flavouring from the milk. Source:Nescafe.com",
image:"https://images.unsplash.com/photo-1591544913896-a2d7dc15a5f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1114&q=80",
price: "3.75",
showMore:false,
},
{
    id:2,
    coffeeName: "New York",
    searchTerm: "Latte",
    description: "A latte or caffè latte is a milk coffee that boasts a silky layer of foam as a real highlight to the drink. A true latte will be made up of one or two shots of espresso, steamed milk and a final, thin layer of frothed milk on top. Source:Nescafe.com",
    image:"https://images.unsplash.com/photo-1467189386127-c4e5e31ee213?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    price: "3.90",
    showMore:false,
},
{
    id:3,
    coffeeName: "Chicago",
    searchTerm: "Americano",
    description: "An americano is quite simply just hot water and espresso. It will either be served 1/2 and 1/2 or 1/3 espresso to 2/3 water. Source:Nescafe.com",
    image:"https://images.unsplash.com/photo-1587985782608-20062892559d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
    price: "2.80",
    showMore:false,
},
{
    id:4,
    coffeeName: "Milan",
    searchTerm: "Espresso",
    description: "Espresso is a delicious concentrated form of coffee, served in shots and it’s often the coffee base of many other beverages, such as cappuccino, latte, americano and macchiato. An espresso is intense and bold, but nonetheless delicious, and the espresso is usually served in small demitasse-style cups for this reason. Source:Nescafe.com",
    image:"https://images.unsplash.com/photo-1508088405209-fbd63b6a4f50?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8ZXNwcmVzc298ZW58MHwwfDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    price: "1.90",
    showMore:false,
},
{
    id:5,
    coffeeName: "Berlin",
    searchTerm: "Flat White",
    description: "A Flat White is a blend of micro-foamed milk poured over a single or double shot of espresso. This microfoam is steamed milk infused with air, to create a smooth and velvety texture and creamy taste. Precise pouring and steaming of the microfoam is essential in making a flat white. Source:Nescafe.com",
    image:"https://images.unsplash.com/photo-1528297506728-9533d2ac3fa4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    price: "4.20",
    showMore:false,
},
{
    id:6,
    coffeeName: "Paris",
    searchTerm: "Frappe",
    description:"The Frappé as the UK know and love is pronounced frap-pay and when loosely translated from French, it literally means ‘iced’. The iced drink is generally made up of water, espresso, sugar, milk, ice and is shaken, blended or beaten to combine the ingredients. It tends to be served with whipped cream and toppings such as sweet sauces and presented in a tall glass. Source:Nescafe.com",
    image:"https://images.unsplash.com/photo-1589396575653-c09c794ff6a6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    price: "4.50",
    showMore:false,
},
{
    id:7,
    coffeeName: "Barcelona",
    searchTerm: "Cortado",
    description:"Unlike other coffee types the milk is not texturised and instead, Cortado coffee is made with lightly steamed milk, no froth or foam. The steamed milk on top reduces the acidity of the coffee and creates a micro-foam which doesn’t separate from the espresso, giving it a strong and rich flavour. Source:Nescafe.com",
    image:"https://images.unsplash.com/photo-1611872515743-b81d6c30605c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    price: "2.10",
    showMore:false,
},
{
    id:8,
    coffeeName: "Moscow",
    searchTerm: "Macchiato",
    description:"The Macchiato is an espresso coffee drink, topped with a small amount of foamed or steamed milk to allow the taste of the espresso to still shine through. Source:Nescafe.com",
    image:"https://images.unsplash.com/photo-1608591038246-4981d06b11e1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=402&q=80",
    price: "3.80",
    showMore:false,
},
{
    id:9,
    coffeeName: "Lisbon",
    searchTerm: "Mocha",
    description:"Deliciously sweet, nutty and chocolatey. This creamy coffee drink is an espresso-based beverage, the basis is that a shot of espresso is combined with a chocolate powder or syrup, followed by milk or cream. It is a variant of a latte, in the sense that it is often 1/3 espresso and 2/3 steamed milk. However, a chocolate flavour is added, and this can be milk or dark. Source:Nescafe.com",
    image:"https://images.unsplash.com/photo-1551727609-1f89c019b5ca?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=998&q=80",
    price: "4.00",
    showMore:false,
},

]
